pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/LinusBwana/alx-backend-python.git'
            }
        }

        stage('Set Up Python Environment') {
            steps {
                withPythonEnv('Python 3') {
                    sh 'pip install -r messaging_app/requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                withPythonEnv('Python 3') {
                    sh 'pytest --junitxml=report.xml'
                }
            }
        }

        stage('Publish Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            deleteDir()
        }
    }
}
