#!/usr/bin/env python3
"""
Fixtures for integration tests
"""

org_payload = {
    "login": "google",
    "id": 1342004,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
    "url": "https://api.github.com/orgs/google",
    "repos_url": "https://api.github.com/orgs/google/repos",
    "events_url": "https://api.github.com/orgs/google/events",
    "hooks_url": "https://api.github.com/orgs/google/hooks",
    "issues_url": "https://api.github.com/orgs/google/issues",
    "members_url": "https://api.github.com/orgs/google/members{/member}",
    "public_members_url": "https://api.github.com/orgs/google/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
    "description": "Google ❤️ Open Source",
    "name": "Google",
    "company": None,
    "blog": "https://opensource.google.com/",
    "location": None,
    "email": "opensource@google.com",
    "twitter_username": None,
    "is_verified": True,
    "has_organization_projects": True,
    "has_repository_projects": True,
    "public_repos": 1341,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "html_url": "https://github.com/google",
    "created_at": "2012-01-18T01:30:18Z",
    "updated_at": "2019-11-06T19:49:26Z",
    "type": "Organization"
}

repos_payload = [
    {
        "id": 7697149,
        "node_id": "MDEwOlJlcG9zaXRvcnk3Njk3MTQ5",
        "name": "episodes.dart",
        "full_name": "google/episodes.dart",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/google",
            "html_url": "https://github.com/google",
            "followers_url": "https://api.github.com/users/google/followers",
            "following_url": "https://api.github.com/users/google/following{/other_user}",
            "gists_url": "https://api.github.com/users/google/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/google/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/google/subscriptions",
            "organizations_url": "https://api.github.com/users/google/orgs",
            "repos_url": "https://api.github.com/users/google/repos",
            "events_url": "https://api.github.com/users/google/events{/privacy}",
            "received_events_url": "https://api.github.com/users/google/received_events",
            "type": "Organization",
            "site_admin": False
        },
        "html_url": "https://github.com/google/episodes.dart",
        "description": "A framework for timing performance of web apps.",
        "fork": False,
        "url": "https://api.github.com/repos/google/episodes.dart",
        "created_at": "2012-11-15T22:31:09Z",
        "updated_at": "2019-09-23T11:53:58Z",
        "pushed_at": "2014-10-09T21:39:33Z",
        "git_url": "git://github.com/google/episodes.dart.git",
        "ssh_url": "git@github.com:google/episodes.dart.git",
        "clone_url": "https://github.com/google/episodes.dart.git",
        "svn_url": "https://github.com/google/episodes.dart",
        "size": 191,
        "stargazers_count": 12,
        "watchers_count": 12,
        "language": "Dart",
        "has_issues": True,
        "has_projects": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 22,
        "mirror_url": None,
        "archived": True,
        "disabled": False,
        "open_issues_count": 0,
        "license": {
            "key": "bsd-3-clause",
            "name": "BSD 3-Clause \"New\" or \"Revised\" License",
            "spdx_id": "BSD-3-Clause",
            "url": "https://api.github.com/licenses/bsd-3-clause",
            "node_id": "MDc6TGljZW5zZTU="
        },
        "forks": 22,
        "open_issues": 0,
        "watchers": 12,
        "default_branch": "master"
    },
    {
        "id": 8566972,
        "node_id": "MDEwOlJlcG9zaXRvcnk4NTY2OTcy",
        "name": "kratu",
        "full_name": "google/kratu",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/google",
            "html_url": "https://github.com/google",
            "type": "Organization",
            "site_admin": False
        },
        "html_url": "https://github.com/google/kratu",
        "description": "Kratu is a client-side analysis framework to create fixed reports",
        "fork": False,
        "url": "https://api.github.com/repos/google/kratu",
        "created_at": "2013-01-04T22:52:33Z",
        "updated_at": "2019-11-15T22:22:16Z",
        "pushed_at": "2013-03-21T23:30:21Z",
        "git_url": "git://github.com/google/kratu.git",
        "ssh_url": "git@github.com:google/kratu.git",
        "clone_url": "https://github.com/google/kratu.git",
        "svn_url": "https://github.com/google/kratu",
        "size": 2377,
        "stargazers_count": 32,
        "watchers_count": 32,
        "language": "JavaScript",
        "has_issues": True,
        "has_projects": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 45,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 0,
        "license": {
            "key": "apache-2.0",
            "name": "Apache License 2.0",
            "spdx_id": "Apache-2.0",
            "url": "https://api.github.com/licenses/apache-2.0",
            "node_id": "MDc6TGljZW5zZTI="
        },
        "forks": 45,
        "open_issues": 0,
        "watchers": 32,
        "default_branch": "master"
    },
    {
        "id": 11730342,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMTczMDM0Mg==",
        "name": "build-debian-cloud",
        "full_name": "google/build-debian-cloud",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/google",
            "html_url": "https://github.com/google",
            "type": "Organization",
            "site_admin": False
        },
        "html_url": "https://github.com/google/build-debian-cloud",
        "description": "Script to create Debian Squeeze & Wheezy images on Google Compute Engine",
        "fork": False,
        "url": "https://api.github.com/repos/google/build-debian-cloud",
        "created_at": "2013-07-23T09:30:26Z",
        "updated_at": "2019-05-09T13:52:22Z",
        "pushed_at": "2014-04-14T17:30:41Z",
        "git_url": "git://github.com/google/build-debian-cloud.git",
        "ssh_url": "git@github.com:google/build-debian-cloud.git",
        "clone_url": "https://github.com/google/build-debian-cloud.git",
        "svn_url": "https://github.com/google/build-debian-cloud",
        "size": 188,
        "stargazers_count": 8,
        "watchers_count": 8,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 25,
        "mirror_url": None,
        "archived": True,
        "disabled": False,
        "open_issues_count": 0,
        "license": None,
        "forks": 25,
        "open_issues": 0,
        "watchers": 8,
        "default_branch": "master"
    }
]

expected_repos = ["episodes.dart", "kratu", "build-debian-cloud"]

apache2_repos = ["kratu"]
