# seed.py

import psycopg2
from psycopg2.extras import RealDictCursor
import uuid

# Sample data
sample_data = [
    {"name": "Alice", "email": "alice@example.com", "age": 25},
    {"name": "Bob", "email": "bob@example.com", "age": 30},
    {"name": "Charlie", "email": "charlie@example.com", "age": 22},
    {"name": "Diana", "email": "diana@example.com", "age": 28},
    {"name": "Johnnie Mayer", "email": "Ross.Reynolds21@hotmail.com", "age": 35},
    {"name": "Myrtle Waters", "email": "Edmund_Funk@gmail.com", "age": 99},
    {"name": "Flora Rodriguez I", "email": "Willie.Bogisich@gmail.com", "age": 84},
    {"name": "Dr. Cecilia Konopelski-Lakin", "email": "Felicia75@gmail.com", "age": 87},
    {"name": "Chelsea Boyle-Stoltenberg", "email": "Regina.Emard97@yahoo.com", "age": 83},
    {"name": "Seth Mraz", "email": "Cecilia_Blanda89@gmail.com", "age": 24},
    {"name": "Thelma Kris-Schinner", "email": "Johnnie.Jast93@hotmail.com", "age": 6},
    {"name": "Thomas Hane", "email": "Dominic24@yahoo.com", "age": 93},
    {"name": "Della Hickle", "email": "Leon_Rohan@hotmail.com", "age": 35},
    {"name": "Kristi Durgan", "email": "Maria_Schmeler9@hotmail.com", "age": 70},
    {"name": "Brad Sawayn", "email": "Tyler.Dach57@gmail.com", "age": 112},
    {"name": "Isabel Crist Jr.", "email": "Cecilia_Braun54@yahoo.com", "age": 63},
    {"name": "Allen Roob", "email": "Sandra.Heidenreich4@yahoo.com", "age": 40},
    {"name": "Robin Wilkinson", "email": "Brent_Wilkinson2@hotmail.com", "age": 62},
    {"name": "Martin Flatley", "email": "Gabriel23@hotmail.com", "age": 13},
    {"name": "Delia Walker IV", "email": "Leticia_Schinner@yahoo.com", "age": 78},
    {"name": "Blanca Durgan", "email": "Christina27@gmail.com", "age": 1},
    {"name": "Ellen Hudson", "email": "Matthew.Medhurst69@gmail.com", "age": 111},
    {"name": "Bobby Bayer", "email": "Erick_Brekke36@gmail.com", "age": 110},
    {"name": "Karen Pfannerstill", "email": "Amber.Steuber-Greenfelder@gmail.com", "age": 49},
    {"name": "Vanessa Kihn-Durgan", "email": "Lorena.Schuppe@hotmail.com", "age": 49},
    {"name": "Grace Sporer", "email": "George38@yahoo.com", "age": 50},
    {"name": "Krista Herzog-Paucek", "email": "Shawn.Tremblay@hotmail.com", "age": 109},
    {"name": "Doyle Schaden", "email": "Clarence.Berge@hotmail.com", "age": 30},
    {"name": "Beth Crooks", "email": "Sean.Bradtke99@yahoo.com", "age": 36},
    {"name": "Doyle Botsford", "email": "Wilfred.Dickinson@hotmail.com", "age": 70},
    {"name": "Santos Skiles", "email": "Joey22@gmail.com", "age": 17},
    {"name": "Ms. Gina Kuhic", "email": "Debbie83@hotmail.com", "age": 78},
    {"name": "Garry Pfeffer", "email": "Lora_Heathcote91@yahoo.com", "age": 105},
    {"name": "Annie Rogahn", "email": "June.Kuhn24@hotmail.com", "age": 92},
    {"name": "Hubert Gerlach", "email": "Alice99@hotmail.com", "age": 3},
    {"name": "Clark Willms", "email": "Leo25@gmail.com", "age": 45},
    {"name": "Natalie Lesch PhD", "email": "Marilyn76@yahoo.com", "age": 76},
    {"name": "Pauline Cremin", "email": "Geraldine.Langworth27@hotmail.com", "age": 50},
    {"name": "Nellie Labadie", "email": "Clay75@hotmail.com", "age": 27},
    {"name": "Felipe Barrows", "email": "Clint37@yahoo.com", "age": 47},
    {"name": "Derrick Mitchell Jr.", "email": "Mark_Fritsch67@hotmail.com", "age": 52},
    {"name": "James Boehm", "email": "Terry9@hotmail.com", "age": 54},
    {"name": "Darrin Fritsch", "email": "Leland.Mills@yahoo.com", "age": 50},
    {"name": "Blanca Osinski", "email": "Annette56@yahoo.com", "age": 96},
    {"name": "Inez Walker", "email": "Fannie_Wolff-Schinner@gmail.com", "age": 19},
    {"name": "Deanna Kunze", "email": "Colleen.Hayes@gmail.com", "age": 109},
    {"name": "Angela Emmerich", "email": "Martin12@yahoo.com", "age": 1},
    {"name": "Sidney Kertzmann", "email": "Angelo_Krajcik@yahoo.com", "age": 10},
    {"name": "Miguel Stokes Sr.", "email": "Sheila86@hotmail.com", "age": 82},
    {"name": "Cedric McLaughlin", "email": "Al.Towne@yahoo.com", "age": 21},
    {"name": "Kendra Hauck", "email": "Jordan1@gmail.com", "age": 58},
    {"name": "Spencer Larson", "email": "Rickey65@gmail.com", "age": 110},
    {"name": "Claudia Collins", "email": "Timothy12@gmail.com", "age": 3},
    {"name": "Ernest Frami", "email": "Elijah_Mante32@gmail.com", "age": 108},
    {"name": "Fred Bailey", "email": "Shaun_Pagac@yahoo.com", "age": 23},
    {"name": "Lillie Feeney MD", "email": "Lester32@hotmail.com", "age": 29},
    {"name": "Salvador Collier", "email": "Alfredo.Bogisich68@gmail.com", "age": 50},
    {"name": "Kathleen Prosacco", "email": "Ervin.Nitzsche16@hotmail.com", "age": 5},
    {"name": "Arlene Bednar", "email": "Rickey7@yahoo.com", "age": 24},
    {"name": "Gayle Towne", "email": "Cora.Nitzsche@yahoo.com", "age": 108},
    {"name": "Alison Carroll", "email": "William.Wisoky@hotmail.com", "age": 5},
    {"name": "Simon Legros", "email": "Lindsey6@gmail.com", "age": 61},
    {"name": "Lucas Larkin", "email": "Chelsea_Kohler@hotmail.com", "age": 20},
    {"name": "Dr. Jerome Jaskolski", "email": "Russell_VonRueden93@yahoo.com", "age": 107},
    {"name": "Delores Friesen", "email": "Shaun.Jacobson21@yahoo.com", "age": 76},
    {"name": "Owen Walker", "email": "Sophie.Will35@yahoo.com", "age": 110},
    {"name": "Danny Rippin", "email": "Darryl_Mann@hotmail.com", "age": 22},
    {"name": "Mona Maggio-Schimmel", "email": "Albert6@hotmail.com", "age": 34},
    {"name": "Dr. Myra Jacobson PhD", "email": "Rudy_Shields59@hotmail.com", "age": 23},
    {"name": "Eunice Crona", "email": "Leland.Harris@hotmail.com", "age": 82},
    {"name": "Essie Ortiz", "email": "Johnnie.Rutherford-Beatty5@yahoo.com", "age": 47},
    {"name": "Lucia Ullrich", "email": "Dallas71@yahoo.com", "age": 81},
    {"name": "Michael Wintheiser", "email": "Brendan_Hilll@hotmail.com", "age": 75},
    {"name": "Tanya Lemke", "email": "Jessie_OConner38@hotmail.com", "age": 117},
    {"name": "Marian Kassulke", "email": "Yvonne25@hotmail.com", "age": 104},
    {"name": "Aubrey Senger", "email": "Darrell.Feeney0@yahoo.com", "age": 62},
    {"name": "Mrs. Alexis Runolfsson", "email": "Krista.Crooks@hotmail.com", "age": 84},
    {"name": "Van Klocko", "email": "Derrick.Collier53@yahoo.com", "age": 95},
    {"name": "Veronica Dicki", "email": "Horace.Gulgowski56@hotmail.com", "age": 3},
    {"name": "Paulette Abshire", "email": "Velma_Flatley26@gmail.com", "age": 25},
    {"name": "Jill Senger MD", "email": "Keith64@hotmail.com", "age": 81},
    {"name": "Betsy Stracke", "email": "Sidney.Wolff38@yahoo.com", "age": 11},
    {"name": "Dr. Ronald Murray", "email": "Billie.Runolfsson@hotmail.com", "age": 15},
    {"name": "Mr. Marc Zieme", "email": "Wendy.Kessler-Adams91@yahoo.com", "age": 53},
    {"name": "Danielle Von", "email": "Delbert.Robel@gmail.com", "age": 34},
    {"name": "Mack Moore", "email": "Sherry45@yahoo.com", "age": 96},
    {"name": "Mrs. Sabrina Cassin", "email": "Marshall_Daugherty20@yahoo.com", "age": 104},
    {"name": "Cameron Bailey", "email": "Anita_Pagac@yahoo.com", "age": 9},
    {"name": "Lewis Nolan Sr.", "email": "Geraldine.Crooks18@gmail.com", "age": 7},
    {"name": "Sally Howell", "email": "Mamie.Parisian@hotmail.com", "age": 97},
    {"name": "Dr. Rosie King", "email": "Dale19@yahoo.com", "age": 51},
    {"name": "Dwight Raynor", "email": "Yvonne_Barrows13@yahoo.com", "age": 65},
    {"name": "Debbie Parker", "email": "George_Bahringer@hotmail.com", "age": 33},
    {"name": "Carolyn Denesik", "email": "Jean.Jacobi@yahoo.com", "age": 5},
    {"name": "Lula Pfeffer", "email": "Inez.Brown25@gmail.com", "age": 22},
    {"name": "Danielle Block", "email": "Lauren_Crooks74@hotmail.com", "age": 109},
    {"name": "Alexis Runolfsdottir DDS", "email": "Dan81@hotmail.com", "age": 41},
    {"name": "Jeremy Weber", "email": "Enrique20@hotmail.com", "age": 75},
    {"name": "Claudia Kreiger", "email": "Krystal.Ziemann27@hotmail.com", "age": 90},
    {"name": "Thomas McLaughlin", "email": "Angelo_Gleichner@yahoo.com", "age": 118},
    {"name": "Bradley Bogisich", "email": "Marlon.Oberbrunner@yahoo.com", "age": 17},
    {"name": "Elsie Schmitt", "email": "Julio55@yahoo.com", "age": 2},
    {"name": "Fernando Wiegand", "email": "Paul.Lindgren59@gmail.com", "age": 20},
    {"name": "Mr. Clay Kirlin-Mann", "email": "Lucia_Powlowski87@yahoo.com", "age": 91},
    {"name": "Grace Vandervort", "email": "Maria_Gulgowski@yahoo.com", "age": 84},
    {"name": "Monica Abbott", "email": "Elsie.Kuphal76@hotmail.com", "age": 88},
    {"name": "Nancy Mueller", "email": "Jimmy_Wolf@yahoo.com", "age": 42},
    {"name": "Andrea Bernier-Abbott", "email": "Forrest43@hotmail.com", "age": 16},
    {"name": "Mr. Carlos Abbott", "email": "Edna_Spinka@hotmail.com", "age": 50},
    {"name": "Carl Tromp-Mraz", "email": "Lucas.Will60@gmail.com", "age": 3},
    {"name": "Irma Kutch", "email": "Marcus65@gmail.com", "age": 77},
    {"name": "Jake Ankunding", "email": "Marion_Hessel58@gmail.com", "age": 75},
    {"name": "Clint Lebsack", "email": "Jennifer.Schimmel@yahoo.com", "age": 22},
    {"name": "Miss Ana Pouros", "email": "Kelvin68@yahoo.com", "age": 80},
    {"name": "Sheldon Daniel", "email": "Stuart.Larkin96@hotmail.com", "age": 113},
    {"name": "Travis Crooks", "email": "Adrienne.OConner71@yahoo.com", "age": 22},
    {"name": "Clifton Dickinson", "email": "Melvin_Bergstrom@yahoo.com", "age": 97},
    {"name": "Saul Waelchi", "email": "Kristi_Connelly70@yahoo.com", "age": 19},
    {"name": "Julie Mueller", "email": "Roger.Jenkins25@hotmail.com", "age": 40},
    {"name": "Estelle Krajcik", "email": "Cristina_Little72@hotmail.com", "age": 63},
    {"name": "Andy Streich", "email": "Marcella.Stanton32@hotmail.com", "age": 21},
    {"name": "Jonathon Volkman", "email": "Irving.Hackett@yahoo.com", "age": 92},
    {"name": "Patti O'Conner-Baumbach", "email": "Irma.Cruickshank@hotmail.com", "age": 6},
    {"name": "Dwayne Gottlieb", "email": "Brandi.Kulas@yahoo.com", "age": 32},
    {"name": "Kellie Howe", "email": "Toni.Legros@hotmail.com", "age": 87},
    {"name": "Mr. Virgil Mraz", "email": "Johnathan33@gmail.com", "age": 23},
    {"name": "Mr. Justin Bosco", "email": "Kurt.Kshlerin@gmail.com", "age": 94},
    {"name": "Stanley Becker", "email": "Charles42@yahoo.com", "age": 33},
    {"name": "Roxanne Koss", "email": "Robin_Zulauf@yahoo.com", "age": 102},
    {"name": "Ann Corkery", "email": "Lana.Kuvalis@hotmail.com", "age": 79},
    {"name": "Danny Witting", "email": "Patsy16@yahoo.com", "age": 3},
    {"name": "Byron Kihn", "email": "Sherri.Dietrich@gmail.com", "age": 17},
    {"name": "Roy Sporer", "email": "Russell_Jast64@gmail.com", "age": 34},
    {"name": "Lois Grimes", "email": "Perry_Bradtke@gmail.com", "age": 52},
    {"name": "Sheldon Hyatt", "email": "Patricia_Terry@gmail.com", "age": 3},
    {"name": "Cecilia Brown", "email": "Blanche.Bergstrom7@yahoo.com", "age": 29},
    {"name": "Nathan Dach-O'Kon", "email": "Morris.Runolfsdottir49@yahoo.com", "age": 100},
    {"name": "Ellis Prohaska", "email": "Ben68@yahoo.com", "age": 58},
    {"name": "Jeffery Reilly", "email": "Adrian.Mitchell1@yahoo.com", "age": 116},
    {"name": "Rodolfo Emmerich", "email": "Betty.Boyer@hotmail.com", "age": 98},
    {"name": "Marcus Reichel", "email": "Guillermo_Spencer@hotmail.com", "age": 72},
    {"name": "Johnathan Hills V", "email": "Kurt59@yahoo.com", "age": 97},
    {"name": "Malcolm Daugherty", "email": "Candice13@hotmail.com", "age": 5},
    {"name": "Hilda Beahan", "email": "Jeanette_Breitenberg55@hotmail.com", "age": 40},
    {"name": "Billie Rippin", "email": "Sadie17@yahoo.com", "age": 78},
    {"name": "Alison Lemke", "email": "Dana33@yahoo.com", "age": 117},
    {"name": "Jamie Nitzsche", "email": "Byron.Bogan50@hotmail.com", "age": 28},
    {"name": "Jason Tillman", "email": "Lydia.Reilly@yahoo.com", "age": 54},
    {"name": "Darryl Orn", "email": "Wilbur.Schmitt@hotmail.com", "age": 21},
    {"name": "Bill Wisoky", "email": "Alexander_Pacocha@hotmail.com", "age": 78},
    {"name": "Mr. Jesus Kunde V", "email": "Rudy37@hotmail.com", "age": 113},
    {"name": "Earnest Mosciski", "email": "Freda32@yahoo.com", "age": 85},
    {"name": "Kristie Krajcik", "email": "Amanda5@hotmail.com", "age": 113},
    {"name": "Misty Erdman-Schulist", "email": "Kelvin96@hotmail.com", "age": 94},
    {"name": "Tanya Champlin", "email": "Garrett.Turner@yahoo.com", "age": 101},
    {"name": "Regina Kuhlman II", "email": "Colleen18@hotmail.com", "age": 91},
    {"name": "Beverly Koch-Runte", "email": "Christian.Herman72@yahoo.com", "age": 91},
    {"name": "Connie Ernser", "email": "Willard55@hotmail.com", "age": 104},
    {"name": "Angelina Bailey DDS", "email": "Terry.Stokes@gmail.com", "age": 54},
    {"name": "Rhonda Altenwerth", "email": "Randolph.Hermann@yahoo.com", "age": 3},
    {"name": "Kelly Bosco-Swift", "email": "Janet29@gmail.com", "age": 3},
    {"name": "Ms. Alyssa Donnelly", "email": "Pat56@hotmail.com", "age": 52},
    {"name": "Delbert Sauer Jr.", "email": "Michelle_Renner58@hotmail.com", "age": 85},
    {"name": "Frank Aufderhar", "email": "Nettie14@gmail.com", "age": 76},
    {"name": "Mr. Kenny Wiegand", "email": "Ken_Kuhn@hotmail.com", "age": 92},
    {"name": "Mr. Eduardo Fisher", "email": "Felicia_Streich@yahoo.com", "age": 57},
    {"name": "Archie Kreiger", "email": "Dennis_Donnelly@gmail.com", "age": 32},
    {"name": "Tanya Swaniawski", "email": "Patty14@hotmail.com", "age": 97},
    {"name": "Edwin Gislason", "email": "Maureen.Smith77@hotmail.com", "age": 100},
    {"name": "Victor Raynor", "email": "Rebecca75@gmail.com", "age": 27},
    {"name": "Claudia Ziemann PhD", "email": "Janet_Krajcik@yahoo.com", "age": 49},
    {"name": "Sylvester Jerde", "email": "Raul.Zulauf18@gmail.com", "age": 30},
    {"name": "Tabitha McClure IV", "email": "Traci8@yahoo.com", "age": 100},
    {"name": "Jaime Zboncak", "email": "Dana18@gmail.com", "age": 39},
    {"name": "Martin Howell", "email": "Teri.Wiza-Cummings85@gmail.com", "age": 24},
    {"name": "Eula Denesik", "email": "Orlando85@gmail.com", "age": 103},
    {"name": "Edmond Jerde", "email": "Eloise.Vandervort55@hotmail.com", "age": 111},
    {"name": "Dianna Gutmann", "email": "Nick_Hackett@yahoo.com", "age": 56},
    {"name": "Irvin Block DDS", "email": "Noel.Lockman85@yahoo.com", "age": 59},
    {"name": "Boyd Feil", "email": "Loren.Veum32@yahoo.com", "age": 27},
    {"name": "Geoffrey Hills", "email": "Robin10@yahoo.com", "age": 56},
    {"name": "Mr. Hector Mayer", "email": "Desiree.Heller@gmail.com", "age": 61},
    {"name": "Frederick Bednar", "email": "Brandy.Boehm@hotmail.com", "age": 31},
    {"name": "Lillian Douglas", "email": "Sheila_Harvey@gmail.com", "age": 24},
    {"name": "Wanda Mohr", "email": "Kathryn_Brown10@hotmail.com", "age": 100},
    {"name": "Dixie Bins", "email": "Cecil35@gmail.com", "age": 113},
    {"name": "Marian Lind-Flatley", "email": "Roger.Hilll34@gmail.com", "age": 65},
    {"name": "Miss Sandra Johnston", "email": "Pedro.Hilll26@hotmail.com", "age": 81},
    {"name": "Lela Crooks", "email": "Robin71@hotmail.com", "age": 21},
    {"name": "Darryl Mraz", "email": "Marta74@hotmail.com", "age": 86},
    {"name": "Shane White", "email": "Penny.Waelchi@yahoo.com", "age": 67},
    {"name": "Tara Hintz MD", "email": "Robin_Kuphal18@gmail.com", "age": 91},
    {"name": "Dr. Jesse Blanda-Weissnat", "email": "Mark.Wiza@yahoo.com", "age": 55},
    {"name": "Josefina Sanford", "email": "Michelle.Prohaska@hotmail.com", "age": 50},
    {"name": "Rosemarie Gutkowski", "email": "Lindsay.McClure-Dibbert20@gmail.com", "age": 29},
    {"name": "Lonnie Davis", "email": "Kathleen.Spinka25@yahoo.com", "age": 48},
    {"name": "Charlotte Kub", "email": "Simon76@yahoo.com", "age": 110},
    {"name": "Dr. Laurence Thiel", "email": "Laurie.Lemke20@yahoo.com", "age": 22},
    {"name": "Dan Willms", "email": "Nichole77@gmail.com", "age": 50},
    {"name": "Shawn Funk", "email": "Suzanne.Koelpin17@gmail.com", "age": 11},
    {"name": "Sherry Morar", "email": "Mario27@hotmail.com", "age": 6},
    {"name": "Sandra Yundt", "email": "Gladys.Gutkowski@yahoo.com", "age": 49},
    {"name": "Miss Olivia Connelly", "email": "Bradford.Runte@hotmail.com", "age": 50},
    {"name": "Vincent Brown", "email": "Cornelius.Fahey@hotmail.com", "age": 30},
    {"name": "Dr. Rosa Howell", "email": "Tara.Schumm43@hotmail.com", "age": 71},
    {"name": "Amy Kilback", "email": "Laurie.Green67@gmail.com", "age": 54},
    {"name": "Sherman Herzog", "email": "Alexis33@yahoo.com", "age": 103},
    {"name": "Shelia Wilkinson", "email": "Dominic78@hotmail.com", "age": 47},
    {"name": "Evelyn Dare IV", "email": "Emanuel_Purdy18@yahoo.com", "age": 5},
    {"name": "Elias Grady", "email": "Melvin.Ritchie85@yahoo.com", "age": 81},
    {"name": "Randy Aufderhar", "email": "Marcos96@hotmail.com", "age": 61},
    {"name": "Damon Moore", "email": "Kristen.Rosenbaum95@gmail.com", "age": 9},
    {"name": "Merle Funk", "email": "Geoffrey.Harber60@gmail.com", "age": 106},
    {"name": "Marcia Buckridge", "email": "Salvatore46@yahoo.com", "age": 48},
    {"name": "Christine Bartoletti", "email": "Gordon76@hotmail.com", "age": 37},
    {"name": "Ms. Christina Herzog", "email": "Rita.Abernathy@hotmail.com", "age": 44},
    {"name": "Milton Herzog I", "email": "Joel_Funk@hotmail.com", "age": 117},
    {"name": "Aaron Will", "email": "Zachary_Harris51@hotmail.com", "age": 85},
    {"name": "Elvira McClure", "email": "Jasmine10@yahoo.com", "age": 45},
    {"name": "Chester Glover", "email": "Jacob59@gmail.com", "age": 117},
    {"name": "Mr. Daniel Hilpert", "email": "Bonnie_Adams35@gmail.com", "age": 12},
    {"name": "Patsy Harber", "email": "Marvin.Swift79@gmail.com", "age": 30},
    {"name": "Nichole Friesen", "email": "Douglas_Krajcik@yahoo.com", "age": 49},
    {"name": "Lewis Gerhold", "email": "Jermaine74@yahoo.com", "age": 3},
    {"name": "Mr. Rick Ankunding", "email": "Rene28@yahoo.com", "age": 86},
    {"name": "Freddie Boyer", "email": "Gene85@yahoo.com", "age": 82},
    {"name": "Ira Armstrong", "email": "Jean_Ernser@yahoo.com", "age": 43},
    {"name": "Miss Anita West", "email": "Beth_Franey2@hotmail.com", "age": 8},
    {"name": "Dexter Jacobson", "email": "Eva_Rice@gmail.com", "age": 109},
    {"name": "Beth Terry", "email": "Elsie10@hotmail.com", "age": 105},
    {"name": "Mr. Mark Cruickshank-Veum", "email": "Dean74@gmail.com", "age": 111},
    {"name": "Dewey Dickens", "email": "Clara_Wisozk77@yahoo.com", "age": 15},
    {"name": "Sean Bartell", "email": "Nora61@hotmail.com", "age": 53},
    {"name": "Ms. Gloria Franecki", "email": "Charlie_Bruen88@yahoo.com", "age": 3},
    {"name": "Erik Flatley", "email": "Marguerite_Ziemann@hotmail.com", "age": 47},
    {"name": "Ian Prosacco Jr.", "email": "Laurie_Ankunding30@hotmail.com", "age": 105},
    {"name": "Zachary Hane", "email": "Christy82@gmail.com", "age": 34},
    {"name": "Dan Wilkinson", "email": "Emmett83@gmail.com", "age": 48},
    {"name": "Josh Littel", "email": "Paulette.Bogisich@yahoo.com", "age": 50},
    {"name": "Tara Reynolds", "email": "Clifford.Schultz@yahoo.com", "age": 36},
    {"name": "Mr. Lonnie Reichert", "email": "Fred_Jakubowski@hotmail.com", "age": 45},
    {"name": "Miss Jessie Cole", "email": "Elmer73@gmail.com", "age": 16},
    {"name": "John Ondricka", "email": "Billy.Koepp@yahoo.com", "age": 30},
    {"name": "Bryant Orn", "email": "Nathaniel.Goyette@yahoo.com", "age": 46},
    {"name": "Ronnie Bechtelar", "email": "Sandra19@yahoo.com", "age": 22},
    {"name": "Darrin Schulist", "email": "Edna53@hotmail.com", "age": 109},
    {"name": "Jeremy Jaskolski", "email": "Walter_Haley@hotmail.com", "age": 26},
    {"name": "Pablo Dietrich", "email": "Rhonda_Kemmer@hotmail.com", "age": 46},
    {"name": "Lisa Emard", "email": "William.Conroy3@gmail.com", "age": 100},
    {"name": "Jo Braun", "email": "Jan_Beatty@gmail.com", "age": 50},
    {"name": "Tiffany Larson", "email": "Victor.Wilkinson-Ullrich@hotmail.com", "age": 97},
    {"name": "Miss Angelina Smitham", "email": "Scott.Price22@hotmail.com", "age": 6},
    {"name": "Darnell Hahn", "email": "Penny.Brakus@gmail.com", "age": 34},
    {"name": "Doreen Lindgren", "email": "Emilio.Reynolds33@yahoo.com", "age": 56},
    {"name": "Keith Kuvalis", "email": "Krista.Weber85@yahoo.com", "age": 69},
    {"name": "Gordon Armstrong", "email": "Angelina_Schoen11@gmail.com", "age": 114},
    {"name": "Dr. Ivan Corwin", "email": "Olivia_Stracke@gmail.com", "age": 34},
    {"name": "Alma Bechtelar", "email": "Shelly_Balistreri22@hotmail.com", "age": 102},
    {"name": "Chelsea Konopelski", "email": "Pamela.Balistreri@yahoo.com", "age": 108},
    {"name": "Mrs. June Skiles", "email": "Maurice.Kris51@yahoo.com", "age": 102},
    {"name": "Gary Barton", "email": "Frederick_Kerluke@gmail.com", "age": 24},
    {"name": "Ms. Francis Harber-Franecki", "email": "Karen_Ratke@gmail.com", "age": 100},
    {"name": "Clay Roberts", "email": "Marlene.Frami35@hotmail.com", "age": 95},
    {"name": "Dwayne Lebsack", "email": "Amber.Carroll45@yahoo.com", "age": 118},
    {"name": "Joshua Wunsch-Harvey", "email": "Guadalupe.Fisher43@yahoo.com", "age": 43},
    {"name": "Roman Huels", "email": "Harriet.Cronin10@yahoo.com", "age": 70},
    {"name": "Josefina Pfannerstill", "email": "Molly.Ortiz42@gmail.com", "age": 68},
    {"name": "Gerard Spinka", "email": "Raul_Conroy74@hotmail.com", "age": 109},
    {"name": "Clifford Kris", "email": "Carol89@hotmail.com", "age": 49},
    {"name": "Bernadette Gulgowski", "email": "Mitchell.Jacobi72@yahoo.com", "age": 50},
    {"name": "Mrs. Angel O'Reilly", "email": "Ella.Heaney@hotmail.com", "age": 115},
    {"name": "Catherine Homenick", "email": "Stella_McKenzie44@gmail.com", "age": 88},
    {"name": "Lorene Kassulke", "email": "Nancy_Leannon@hotmail.com", "age": 55},
    {"name": "Harriet Murazik", "email": "Sophia66@gmail.com", "age": 119},
    {"name": "Elizabeth Monahan", "email": "Levi.Powlowski7@hotmail.com", "age": 75},
    {"name": "Mario Kassulke", "email": "Joshua_Borer@gmail.com", "age": 30},
    {"name": "Helen Bernhard", "email": "Robert98@yahoo.com", "age": 65},
    {"name": "Ms. Sue Harris", "email": "Calvin.Abshire23@yahoo.com", "age": 80},
    {"name": "Erik Friesen", "email": "Mary_Spencer60@gmail.com", "age": 25},
    {"name": "Vera Funk", "email": "Stewart_Jast@yahoo.com", "age": 117},
    {"name": "Everett Ryan", "email": "Sherri_Macejkovic61@gmail.com", "age": 66},
    {"name": "Cora Zieme-Schinner", "email": "Clifford66@hotmail.com", "age": 82},
    {"name": "Melanie Hessel", "email": "Kristine6@gmail.com", "age": 93},
    {"name": "Miss Michele Okuneva", "email": "Jennie_Purdy@yahoo.com", "age": 87},
    {"name": "Travis Rice V", "email": "Elmer_Terry34@gmail.com", "age": 61},
    {"name": "Wilson Schmitt", "email": "Jermaine.Spinka75@yahoo.com", "age": 55},
    {"name": "Rita Bernhard", "email": "Kara.Rutherford89@hotmail.com", "age": 67},
    {"name": "Lionel Graham Jr.", "email": "Marie_Nitzsche3@hotmail.com", "age": 99},
    {"name": "Larry Heathcote", "email": "Francisco15@hotmail.com", "age": 23},
    {"name": "Benny Feil", "email": "Opal.Smitham25@gmail.com", "age": 53},
    {"name": "Dr. Gerard Krajcik", "email": "Clayton_Mitchell67@gmail.com", "age": 60},
    {"name": "Jessica Leffler", "email": "Terri64@gmail.com", "age": 17},
    {"name": "Mrs. Meredith Rowe", "email": "Beverly_Cruickshank@hotmail.com", "age": 88},
    {"name": "Brian Hettinger-Bode", "email": "Laurie34@hotmail.com", "age": 54},
    {"name": "Herman Green", "email": "Lauren_Halvorson23@hotmail.com", "age": 61},
    {"name": "Carla Nader", "email": "Cesar_Zieme90@yahoo.com", "age": 103},
    {"name": "Dan Altenwerth Jr.", "email": "Molly59@gmail.com", "age": 67},
    {"name": "Christy Bode", "email": "Cameron5@yahoo.com", "age": 9},
    {"name": "Darrel Denesik", "email": "Rolando.Borer48@gmail.com", "age": 5},
    {"name": "Molly Emard", "email": "Deanna88@hotmail.com", "age": 111},
    {"name": "Forrest Nader", "email": "Marcella.Blanda61@yahoo.com", "age": 75},
    {"name": "Mr. Calvin Rippin II", "email": "Ann.Kessler@yahoo.com", "age": 10},
    {"name": "June Walker", "email": "Joann40@hotmail.com", "age": 8},
    {"name": "Ms. Evelyn Conn", "email": "Eunice_Johns@hotmail.com", "age": 73},
    {"name": "Sara Ledner", "email": "Alexandra62@yahoo.com", "age": 18},
    {"name": "Randall Koepp", "email": "Marcos71@yahoo.com", "age": 28},
    {"name": "Stewart Deckow", "email": "Brenda_Harris25@hotmail.com", "age": 58},
    {"name": "Alejandro Goyette MD", "email": "Jesse_Schmeler@yahoo.com", "age": 31},
    {"name": "Ms. Virginia Bernier", "email": "Brian.Walker71@gmail.com", "age": 52},
    {"name": "Mr. Jaime Watsica", "email": "Lula54@gmail.com", "age": 53},
    {"name": "Ms. Tricia Lockman", "email": "Curtis.Pfannerstill@yahoo.com", "age": 94},
    {"name": "Darla Hartmann", "email": "Cesar.Luettgen@gmail.com", "age": 85},
    {"name": "Gregory Mayer", "email": "Rolando32@yahoo.com", "age": 98},
    {"name": "Duane Daugherty", "email": "Andy_Ziemann68@yahoo.com", "age": 110},
    {"name": "Anne Waters", "email": "Debra39@gmail.com", "age": 14},
    {"name": "Dr. Lee Hintz-Krajcik V", "email": "Cary84@gmail.com", "age": 97},
    {"name": "Alex Kreiger", "email": "Noel.Lakin93@gmail.com", "age": 31},
    {"name": "Erma Kuvalis", "email": "Andy69@gmail.com", "age": 86},
    {"name": "Tracy Howell", "email": "Abraham.Kreiger@gmail.com", "age": 34},
    {"name": "Danielle Thiel", "email": "Emily_Lebsack11@hotmail.com", "age": 47},
    {"name": "Mr. Cameron Hyatt", "email": "Willie70@hotmail.com", "age": 109},
    {"name": "Stacey Wisoky", "email": "Mindy_Dietrich48@gmail.com", "age": 8},
    {"name": "Vernon Buckridge", "email": "Roberto_Champlin@yahoo.com", "age": 53},
    {"name": "Mercedes Larson Jr.", "email": "Emma.Conn@yahoo.com", "age": 61},
    {"name": "Samantha Predovic", "email": "Horace.Lowe97@yahoo.com", "age": 82},
    {"name": "Mr. Frankie Collier Jr.", "email": "Suzanne95@hotmail.com", "age": 53},
    {"name": "Leroy Bogan", "email": "Ella8@gmail.com", "age": 59},
    {"name": "Samantha Terry", "email": "Cary_Batz@hotmail.com", "age": 120},
    {"name": "Randolph Wiza DDS", "email": "Lindsay_Bode@yahoo.com", "age": 116},
    {"name": "Troy Bode", "email": "Gerardo77@gmail.com", "age": 60},
    {"name": "Rex Ortiz-Wilderman II", "email": "Harry72@yahoo.com", "age": 99},
    {"name": "May Bartoletti", "email": "Alyssa_Dare@gmail.com", "age": 116},
    {"name": "Roman Kihn", "email": "Carolyn.Schultz94@hotmail.com", "age": 116},
    {"name": "Carlton Torp Jr.", "email": "Anne_Grimes18@hotmail.com", "age": 23},
    {"name": "Kara Kirlin", "email": "Erik91@gmail.com", "age": 72},
    {"name": "Pat Hammes", "email": "Shawn_Davis@yahoo.com", "age": 36},
    {"name": "Anita Hauck", "email": "Patty90@yahoo.com", "age": 33},
    {"name": "Byron Harvey-Quitzon", "email": "Sara_Willms@gmail.com", "age": 27},
    {"name": "Kathleen Corwin", "email": "Bernadette4@hotmail.com", "age": 115},
    {"name": "Kristin Daniel", "email": "Jodi.Gislason@yahoo.com", "age": 25},
    {"name": "Irma Spencer I", "email": "Kristopher_Kautzer@yahoo.com", "age": 19},
    {"name": "Jeannie McLaughlin", "email": "Hattie_Tromp@hotmail.com", "age": 28},
    {"name": "Dr. Vincent Torphy", "email": "Alice_Deckow15@gmail.com", "age": 105},
    {"name": "Darrel Batz-Roberts", "email": "Jessie4@yahoo.com", "age": 76},
    {"name": "Harold Reichel", "email": "Gina.Goyette@gmail.com", "age": 80},
    {"name": "Roman Lubowitz", "email": "Boyd.Bruen-Friesen@gmail.com", "age": 43},
    {"name": "Melody Walsh", "email": "Spencer98@yahoo.com", "age": 41},
    {"name": "Elbert Upton", "email": "Felix.Yundt30@hotmail.com", "age": 107},
    {"name": "Shannon Ankunding", "email": "Ronnie32@yahoo.com", "age": 61},
    {"name": "Ben Rath", "email": "Dave.Bernhard43@hotmail.com", "age": 68},
    {"name": "Raymond Lakin", "email": "Kate_Okuneva@gmail.com", "age": 81},
    {"name": "Oliver Donnelly", "email": "Conrad48@hotmail.com", "age": 36},
    {"name": "Cristina Marks", "email": "Nettie_Graham44@yahoo.com", "age": 114},
    {"name": "Cameron Grady", "email": "Ann52@yahoo.com", "age": 21},
    {"name": "Mr. Leonard Huel", "email": "Shawna.Veum34@gmail.com", "age": 21},
    {"name": "Brittany Cremin", "email": "Beulah.Krajcik@yahoo.com", "age": 78},
    {"name": "Vincent Rodriguez", "email": "Blanca.Miller@gmail.com", "age": 61},
    {"name": "Darryl Vandervort", "email": "Victor.Upton@yahoo.com", "age": 42},
    {"name": "Heather Cummings", "email": "Vivian14@hotmail.com", "age": 24},
    {"name": "Mabel Gleason", "email": "Nathaniel_Mertz94@yahoo.com", "age": 106},
    {"name": "Dennis Herzog", "email": "Rosemarie_Schoen47@hotmail.com", "age": 85},
    {"name": "Tina Nitzsche DVM", "email": "Eva_Dickinson@hotmail.com", "age": 115},
    {"name": "Wallace Gorczany", "email": "Belinda_Frami@yahoo.com", "age": 50},
    {"name": "Dr. Sheldon Brakus", "email": "Noah_Rau@gmail.com", "age": 80},
    {"name": "Stephanie Murazik", "email": "Morris95@gmail.com", "age": 109},
    {"name": "Sara Schoen", "email": "Grady52@gmail.com", "age": 27},
    {"name": "Mrs. Veronica Nikolaus", "email": "Todd.Altenwerth35@gmail.com", "age": 95},
    {"name": "Dr. Amos Swift Sr.", "email": "Teri67@hotmail.com", "age": 7},
    {"name": "Milton Mraz", "email": "Beth8@yahoo.com", "age": 66},
    {"name": "Willard Runte", "email": "Vernon.Kunde@hotmail.com", "age": 98},
    {"name": "Wanda Willms", "email": "Daniel98@hotmail.com", "age": 61},
    {"name": "Andres Pfannerstill", "email": "Nicolas_Ankunding34@gmail.com", "age": 81},
    {"name": "Carl Medhurst I", "email": "Jesse93@yahoo.com", "age": 94},
    {"name": "Dr. Kirk Sipes", "email": "Janis_Powlowski54@hotmail.com", "age": 98},
    {"name": "Kathleen Herzog", "email": "Yvette_Bergstrom-Mertz28@yahoo.com", "age": 91},
    {"name": "Elvira Bergstrom", "email": "Karen_Lockman0@yahoo.com", "age": 61},
    {"name": "Casey Boehm", "email": "Rene_Johns@hotmail.com", "age": 99},
    {"name": "Lynette Walter", "email": "Lester.Wiegand-Lindgren@hotmail.com", "age": 12},
    {"name": "Ellis Douglas", "email": "Dawn_Kuhn@yahoo.com", "age": 61},
    {"name": "Jean Quitzon", "email": "Kate52@yahoo.com", "age": 99},
    {"name": "Rosemarie Bogan", "email": "Edwin98@gmail.com", "age": 70},
    {"name": "Harold Bailey", "email": "Gwen_Weber18@gmail.com", "age": 116},
    {"name": "Judith O'Reilly PhD", "email": "Jaime.Schulist@hotmail.com", "age": 115},
    {"name": "Marguerite Marks", "email": "Rosie_Keeling50@gmail.com", "age": 2},
    {"name": "Hugo MacGyver", "email": "Brad99@yahoo.com", "age": 25},
    {"name": "Tyler Kohler Jr.", "email": "Carolyn_Quigley94@yahoo.com", "age": 117},
    {"name": "Ms. Florence Herzog", "email": "Lynn_Kuvalis@yahoo.com", "age": 19},
    {"name": "Theodore Powlowski", "email": "Erick89@yahoo.com", "age": 52},
    {"name": "Conrad Daniel", "email": "Alberta_Gorczany@yahoo.com", "age": 74},
    {"name": "Christina Spencer", "email": "Kelly93@hotmail.com", "age": 65},
    {"name": "Jacquelyn Gerlach", "email": "Antonio29@hotmail.com", "age": 82},
    {"name": "Lynette Sporer", "email": "Leona.Gutkowski9@gmail.com", "age": 36},
    {"name": "Victoria Bashirian", "email": "Rachel_Fay@yahoo.com", "age": 83},
    {"name": "Mrs. Amy Hamill DDS", "email": "Charles_Schumm@yahoo.com", "age": 12},
    {"name": "Guadalupe Ledner", "email": "Paula25@yahoo.com", "age": 70},
    {"name": "Rickey Zemlak", "email": "Belinda46@hotmail.com", "age": 77},
    {"name": "Jaime Hegmann III", "email": "Todd17@hotmail.com", "age": 58},
    {"name": "Darren Christiansen", "email": "Aaron.Streich90@hotmail.com", "age": 83},
    {"name": "Sandy Bashirian", "email": "Melvin_Davis4@yahoo.com", "age": 87},
    {"name": "Roman Keebler", "email": "Celia_Berge@yahoo.com", "age": 98},
    {"name": "Denise Orn", "email": "Annie.Schuster@hotmail.com", "age": 117},
    {"name": "Dr. Angelo Littel", "email": "Evelyn_Rau@yahoo.com", "age": 113},
    {"name": "Joanna Strosin", "email": "Tamara59@hotmail.com", "age": 113},
    {"name": "Mr. Stanley Reinger", "email": "Felipe.Smith@hotmail.com", "age": 37},
    {"name": "Marion Leffler", "email": "William47@hotmail.com", "age": 54},
    {"name": "Carolyn Boyle II", "email": "Tanya76@yahoo.com", "age": 16},
    {"name": "Deanna Breitenberg", "email": "Jimmy60@yahoo.com", "age": 107},
    {"name": "Dominick Conroy PhD", "email": "Guadalupe_Langosh-Reichert41@hotmail.com", "age": 75},
    {"name": "Stanley Quigley-Marks", "email": "Lana_Vandervort@yahoo.com", "age": 80},
    {"name": "Chad Gutkowski", "email": "Jerry.Wintheiser1@hotmail.com", "age": 46},
    {"name": "Monica Pollich", "email": "Samuel_Dietrich@gmail.com", "age": 97},
    {"name": "Claudia Anderson V", "email": "Esther77@hotmail.com", "age": 96},
    {"name": "Tracey Hoeger", "email": "Bennie47@gmail.com", "age": 7},
    {"name": "Jennie Lehner", "email": "Amber.Mayer@yahoo.com", "age": 69},
    {"name": "Johanna Rice-Miller", "email": "Charlie.Klein73@yahoo.com", "age": 87},
    {"name": "Ms. Valerie Mante", "email": "Dan57@gmail.com", "age": 51},
    {"name": "Leona Kiehn", "email": "Lonnie_Becker@hotmail.com", "age": 37},
    {"name": "Adrienne Lang", "email": "Mildred_Maggio52@hotmail.com", "age": 19},
    {"name": "Ray Mosciski", "email": "Henry_Schimmel9@gmail.com", "age": 17},
    {"name": "Jody Harris", "email": "Catherine_Bartell@hotmail.com", "age": 116},
    {"name": "Kendra Pfannerstill II", "email": "Olive_Abbott@gmail.com", "age": 41},
    {"name": "Alyssa Stanton", "email": "Kay_Morar63@yahoo.com", "age": 41},
    {"name": "Sheryl Bashirian", "email": "Norma.Jacobs@hotmail.com", "age": 108},
    {"name": "Lauren Veum", "email": "Candice_Bergnaum@hotmail.com", "age": 2},
    {"name": "Jacob McCullough", "email": "Homer_Waters@hotmail.com", "age": 54},
    {"name": "Patti Stokes", "email": "Rachel_Lind15@gmail.com", "age": 34},
    {"name": "Heather Blanda", "email": "Yvonne_Pollich18@gmail.com", "age": 70},
    {"name": "Theodore Friesen-Konopelski", "email": "Diane99@hotmail.com", "age": 81},
    {"name": "Glenda Wisozk", "email": "Miriam21@gmail.com", "age": 119},
    {"name": "Linda Waelchi", "email": "Chester_Funk69@yahoo.com", "age": 76},
    {"name": "Natasha Fahey", "email": "Jamie.Koss77@gmail.com", "age": 77},
    {"name": "Becky Schroeder", "email": "Lynne44@gmail.com", "age": 69},
    {"name": "Gayle Schneider DDS", "email": "Amelia.Rolfson@gmail.com", "age": 92},
    {"name": "Allison Mohr", "email": "Dustin.Kunze@hotmail.com", "age": 52},
    {"name": "Miss Melody Krajcik", "email": "Ebony_Gleason@gmail.com", "age": 69},
    {"name": "Amanda Thompson", "email": "Erin_Herman-Dach9@gmail.com", "age": 43},
    {"name": "Wilfred Hackett", "email": "Julian.Hudson@yahoo.com", "age": 19},
    {"name": "Jason Abbott DDS", "email": "April_Prohaska2@gmail.com", "age": 62},
    {"name": "Kelli Blanda", "email": "Alfred63@yahoo.com", "age": 106},
    {"name": "Viola Zulauf Sr.", "email": "Diana.Ledner92@yahoo.com", "age": 52},
    {"name": "Ivan Harvey", "email": "Rex10@yahoo.com", "age": 30},
    {"name": "Jeff Koss", "email": "Dora.Mann80@gmail.com", "age": 104},
    {"name": "Gene Feest Sr.", "email": "Ted59@gmail.com", "age": 64},
    {"name": "Debbie Hyatt", "email": "Marcus86@hotmail.com", "age": 22},
    {"name": "Russell Haley", "email": "Jenny5@yahoo.com", "age": 73},
    {"name": "Naomi Ruecker", "email": "Clifton.Sanford3@hotmail.com", "age": 84},
    {"name": "Carole Treutel", "email": "Darryl.Aufderhar32@hotmail.com", "age": 75},
    {"name": "Rebecca Steuber", "email": "Julian91@gmail.com", "age": 83},
    {"name": "Dorothy Kling", "email": "Yvette_Lynch44@yahoo.com", "age": 23},
    {"name": "Leona O'Reilly", "email": "Gregory.Fisher@hotmail.com", "age": 52},
    {"name": "Rita Satterfield", "email": "Pam.Collier-Homenick@gmail.com", "age": 32},
    {"name": "Jessie Kulas", "email": "Cynthia47@yahoo.com", "age": 107},
    {"name": "Linda Runte", "email": "Viola_Rodriguez17@hotmail.com", "age": 21},
    {"name": "Janice Altenwerth", "email": "Byron_Turner74@gmail.com", "age": 72},
    {"name": "Cecilia Murray", "email": "Kenneth.Douglas@hotmail.com", "age": 118},
    {"name": "Estelle Bartell V", "email": "Gabriel28@hotmail.com", "age": 115},
    {"name": "Kyle Breitenberg", "email": "Irvin.Mosciski35@gmail.com", "age": 38},
    {"name": "Dr. Earnest Kuhlman", "email": "Joanne.Christiansen@gmail.com", "age": 91},
    {"name": "Stephanie Reichert", "email": "Doreen25@gmail.com", "age": 58},
    {"name": "Carla Hoeger", "email": "Phillip.Sauer@yahoo.com", "age": 33},
    {"name": "Timmy Donnelly", "email": "Ernest.Feil44@yahoo.com", "age": 26},
    {"name": "Tiffany Kub-Friesen", "email": "Ryan2@yahoo.com", "age": 23},
    {"name": "Sammy Waters", "email": "Marta_Rutherford@hotmail.com", "age": 70},
    {"name": "Edith Schaefer", "email": "Beverly_Trantow@gmail.com", "age": 48},
    {"name": "Wendy Paucek", "email": "Anthony_Smitham81@yahoo.com", "age": 84},
    {"name": "Robyn Luettgen", "email": "Dorothy82@gmail.com", "age": 100},
    {"name": "Mrs. Madeline Luettgen", "email": "Susan36@hotmail.com", "age": 20},
    {"name": "Barry Sauer", "email": "Teresa_Douglas48@hotmail.com", "age": 75},
    {"name": "Leland Corwin", "email": "Robert_Zieme@gmail.com", "age": 38},
    {"name": "Troy Huels", "email": "Alex_Windler@yahoo.com", "age": 32},
    {"name": "Wilson Lebsack", "email": "Edith21@gmail.com", "age": 80},
    {"name": "Elsa Price Sr.", "email": "Rufus.Langworth@hotmail.com", "age": 63},
    {"name": "Connie McClure", "email": "Erin_Breitenberg@yahoo.com", "age": 72},
    {"name": "Toni Jaskolski", "email": "Ivan15@yahoo.com", "age": 111},
    {"name": "Jessica Bartell", "email": "Arlene_Bradtke@gmail.com", "age": 44},
    {"name": "Sadie Toy", "email": "Randolph39@hotmail.com", "age": 67},
    {"name": "Alonzo Boyer", "email": "Marian_Schiller88@hotmail.com", "age": 19},
    {"name": "Pete Smith", "email": "Lynette48@gmail.com", "age": 103},
    {"name": "Travis Luettgen", "email": "Blanca_Kiehn81@hotmail.com", "age": 118},
]

# ------------------ Database connection ------------------ #
def connect_db():
    """Connect to PostgreSQL server (default database: postgres)."""
    try:
        conn = psycopg2.connect(
            host="localhost",
            user="postgres",
            password="Blue@1996",
            dbname="postgres"
        )
        conn.autocommit = True
        return conn
    except Exception as e:
        print(f"Error connecting to PostgreSQL: {e}")
        return None

def create_database(connection):
    """Create ALX_prodev database if it does not exist."""
    cursor = connection.cursor()
    try:
        cursor.execute("SELECT 1 FROM pg_database WHERE datname='ALX_prodev'")
        exists = cursor.fetchone()
        if not exists:
            cursor.execute("CREATE DATABASE ALX_prodev")
            print("Database ALX_prodev created.")
        else:
            print("Database ALX_prodev already exists.")
    except Exception as e:
        print(f"Error creating database: {e}")
    finally:
        cursor.close()

def connect_to_prodev():
    """Connect to ALX_prodev database."""
    try:
        conn = psycopg2.connect(
            host="localhost",
            user="postgres",
            password="Blue@1996",  #
            dbname="ALX_prodev"
        )
        conn.autocommit = True
        return conn
    except Exception as e:
        print(f"Error connecting to ALX_prodev: {e}")
        return None

# ------------------ Table creation ------------------ #
def create_table(connection):
    """Create user_data table if not exists."""
    cursor = connection.cursor()
    create_table_query = """
    CREATE TABLE IF NOT EXISTS user_data (
        user_id UUID PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE,
        age NUMERIC NOT NULL
    )
    """
    try:
        cursor.execute(create_table_query)
        print("Table user_data ensured.")
    except Exception as e:
        print(f"Error creating table: {e}")
    finally:
        cursor.close()

# ------------------ Insert data ------------------ #
def insert_data(connection, data):
    """Insert sample data into user_data table."""
    cursor = connection.cursor()
    insert_query = """
    INSERT INTO user_data (user_id, name, email, age)
    VALUES (%s, %s, %s, %s)
    ON CONFLICT (email) DO UPDATE 
        SET name = EXCLUDED.name, age = EXCLUDED.age
    """
    try:
        for row in data:
            cursor.execute(insert_query, (str(uuid.uuid4()), row['name'], row['email'], row['age']))
        print("Data inserted/updated successfully.")
    except Exception as e:
        print(f"Error inserting data: {e}")
    finally:
        cursor.close()

# ------------------ Generator ------------------ #
def stream_users(connection):
    """Generator to yield rows one by one."""
    cursor = connection.cursor(cursor_factory=RealDictCursor)
    cursor.execute("SELECT * FROM user_data")
    for row in cursor:
        yield row
    cursor.close()

# ------------------ Main ------------------ #
if __name__ == "__main__":
    conn = connect_db()
    if conn:
        create_database(conn)
        conn.close()

    conn = connect_to_prodev()
    if conn:
        create_table(conn)
        insert_data(conn, sample_data)

        print("\nStreaming users from database:")
        for user in stream_users(conn):
            print(user)

        conn.close()