name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: LinusBwana
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t LinusBwana/messaging_app:latest .
          docker tag LinusBwana/messaging_app:latest LinusBwana/messaging_app:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push LinusBwana/messaging_app:latest
          docker push LinusBwana/messaging_app:${{ github.sha }}