# Generated by Django 5.2.6 on 2025-09-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversation_id',
            new_name='conversation',
        ),
    ]
