version: '3.9'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    image: messaging_app
    command: sh -c "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: